---
- hosts: 127.0.0.1

  vars_files:
    - env.yaml


  tasks:

  - name: Install nginx
    action: yum name=nginx

  - name: Configure nginx
    action: template src=nginx-default.conf dest=/etc/nginx/conf.d/default.conf
    notify:
    - restart nginx

  - name: Ensure nginx is running
    action: service name=nginx state=started


  handlers:
  - name: restart nginx
    action: service name=nginx state=restarted
